services:
  # node:
  #   image: node:20-alpine
  #   working_dir: /var/www/html
  #   volumes:
  #     - ./:/var/www/html
  #   command: sh -c "npm install && npm run build"
  #   networks:
  #     - laravel_network

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      # - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-laravel_db}
      DB_USERNAME: ${DB_USERNAME:-laravel_user}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      - db
    networks:
      - laravel_network
    command: |
      sh -c "
      # Copy .env if it does not exist
      if [ ! -f /var/www/html/.env ]; then
        cp /var/www/html/.env.example /var/www/html/.env
        php artisan key:generate --ansi
      fi ;

      # Set permissions
      chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache ;

      # Install dependencies and run migrations
      cd /var/www/html && composer install --no-interaction --optimize-autoloader &&
      php artisan migrate --seed && php artisan optimize:clear ;

      # Start PHP-FPM
      php-fpm -F
      "

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel_db}
      POSTGRES_USER: ${DB_USERNAME:-laravel_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_network

volumes:
  pgdata:

networks:
  laravel_network:
    driver: bridge
